### ISSUE TITLE
ENV variables coming through as labels instead of values

### ISSUE THREAD

**Issue by drafie** [peec/laravel-aws#1]
Great work on this project.  Thank you for making it public. 

I am trying to get this up and running, but the **eb deploy** always fails.  It seems to be because the environment variables are not coming through with real values.   

Looking in the AWS BeanStalk Console under Configuration/Software/Environment - I see values like this:

MEDIA_S3_DOMAIN_NAME         `{"Fn::GetAtt" : [ "MediaBucket", "DomainName" ]}`
MEDIA_S3_REGION                       `{"Ref": "AWS::Region"}`

Now, I see that you had put in place a fix for this - but it doesn't seem to be working for some reason.   Does **eb deploy**  still work for you?

The specific error is:

Current state: 'CREATE_FAILED'  Reason: The following resource(s) failed to create: [MyCacheSecurityGroup, MediaBucket, MediaUser, LaravelSQSQueue, SQSUser, AWSEBLoadBalancerSecurityGroup].

**Comment by drafie** [comment]
Just to add a little more detail.   I ssh'd into the server and found that /tmp/envs does not exist.

**Comment by drafie** [comment]
Solved.   Bottom line problem - make sure the user executing the **eb create** command has privileges to create IAM users.

**Comment by mehmetsefabalik** [comment]
@drafie  Which user should has those privileges, local user or aws user? and how to add privileges to create IAM users?

**Comment by Martin-Eckleben** [comment]
+1 please reopen
