### ISSUE TITLE
The following resource failed to create: [AWSEBInstanceLaunchWaitCondition]

### ISSUE THREAD

**Issue by mehmetsefabalik** [peec/laravel-aws#3]
I am getting this error after  `eb create` command:

`$ eb create --database --database.engine mysql --database.instance db.t2.micro --database.size 10 -i t2.micro --database.username ebroot --database.password mydbpassword321 myapp-prod --timeout 45
WARNING: The Multi-container Docker platform requires additional ECS permissions. Add the permissions to the aws-elasticbeanstalk-ec2-role or use your own instance profile by typing "-ip {profile-name}".
For more information see: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_ecs.html#create_deploy_docker_ecs_role
Creating application version archive "app-1855-171124_003718".
Uploading laravel-aws/app-1855-171124_003718.zip to S3. This may take a while.
Upload Complete.
Environment details for: myapp-prod
  Application name: laravel-aws
  Region: eu-west-1
  Deployed Version: app-1855-171124_003718
  Environment ID: e-iubp36kmmj
  Platform: arn:aws:elasticbeanstalk:eu-west-1::platform/Multi-container Docker running on 64bit Amazon Linux/2.7.5
  Tier: WebServer-Standard
  CNAME: UNKNOWN
  Updated: 2017-11-23 21:37:32.016000+00:00
Printing Status:
INFO: createEnvironment is starting.
INFO: Using elasticbeanstalk-eu-west-1-799879965789 as Amazon S3 storage bucket for environment data.
INFO: Created security group named: sg-c5d25abe
INFO: Created load balancer named: awseb-e-i-AWSEBLoa-1IKCYBTJC3P7O
INFO: Created security group named: awseb-e-iubp36kmmj-stack-AWSEBSecurityGroup-GICFVUTTIJN7
INFO: Created Auto Scaling launch configuration named: awseb-e-iubp36kmmj-stack-AWSEBAutoScalingLaunchConfiguration-AQH6T5UP01XX
INFO: Created RDS database security group named: awseb-e-iubp36kmmj-stack-awsebrdsdbsecuritygroup-1dsfi2zq7ekag
INFO: Creating RDS database named: aa1a4ra5vuj2rk6. This may take a few minutes.
INFO: Created RDS database named: aa1a4ra5vuj2rk6
INFO: Created Auto Scaling group named: awseb-e-iubp36kmmj-stack-AWSEBAutoScalingGroup-1BJYJK1FVG9RY
INFO: Waiting for EC2 instances to launch. This may take a few minutes.
INFO: Created Auto Scaling group policy named: arn:aws:autoscaling:eu-west-1:799879965789:scalingPolicy:4259b1b5-c5e0-4eae-9a19-38c0514c6a71:autoScalingGroupName/awseb-e-iubp36kmmj-stack-AWSEBAutoScalingGroup-1BJYJK1FVG9RY:policyName/awseb-e-iubp36kmmj-stack-AWSEBAutoScalingScaleUpPolicy-81LRJV7CLC3T
INFO: Created CloudWatch alarm named: awseb-e-iubp36kmmj-stack-AWSEBCloudwatchAlarmLow-4AGZS9ZMXQIM
INFO: Created CloudWatch alarm named: awseb-e-iubp36kmmj-stack-AWSEBCloudwatchAlarmHigh-RVPBT78DKBPJ
ERROR: Stack named 'awseb-e-iubp36kmmj-stack' aborted operation. Current state: 'CREATE_FAILED'  Reason: The following resource(s) failed to create: [AWSEBInstanceLaunchWaitCondition].
ERROR: LaunchWaitCondition failed. The expected number of EC2 instances were not initialized within the given time. Rebuild the environment. If this persists, contact support.
INFO: Launched environment: myapp-prod. However, there were issues during launch. See event log for details.`

Any help would be appreciated.

**Comment by peec** [comment]
Hello,

You must add managed permission (AWSElasticBeanstalkMulticontainerDocker) to the `aws-elasticbeanstalk-ec2-role` role in AWS IAM. See:

http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/iam-instanceprofile.html

**Comment by mehmetsefabalik** [comment]
Hey I actually added  AWSElasticBeanstalkMulticontainerDocker) to the aws-elasticbeanstalk-ec2-role. 
There is something else wrong.

here is ss: https://docs.google.com/uc?export=download&id=1XRWrj5bbzxwjcKw0k_ZN0t-h7ti__kPY

**Comment by mehmetsefabalik** [comment]
Please open the issue again.

**Comment by stephen-gobin** [comment]
I'm having the same issue. Has there been any updates? Thanks!

**Comment by valentinceaprazaru** [comment]
Hello,

i get : 

ERROR: Stack named 'awseb-e-m2bw939qqf-stack' aborted operation. Current state: 'CREATE_FAILED'  Reason: The following resource(s) failed to create: [MediaCDN, MyCacheSecurityGroupIngress, MyElastiCache]. 

Or : 

ERROR: Stack named 'awseb-e-p4vmcgtrrh-stack' aborted operation. Current state: 'CREATE_FAILED'  Reason: The following resource(s) failed to create: [MyCacheSecurityGroup, MediaBucket, MediaUser, LaravelSQSQueue, SQSUser, AWSEBLoadBalancerSecurityGroup]. 
ERROR: Creating security group named: awseb-e-p4vmcgtrrh-stack-AWSEBLoadBalancerSecurityGroup-13KSD9QRMF9AI failed Reason: Resource creation cancelled

I have followed all your instructions on the README page.

**Comment by Martin-Eckleben** [comment]
+1
"Stack named 'awseb-e-jxnn2setvy-stack' aborted operation. Current state: 'CREATE_FAILED' Reason: The following resource(s) failed to create: [MediaUser, LaravelSQSQueue, AWSEBBeanstalkMetadata, SQSUser]."

EDIT: pressing actions->Rebuild Environment button in AWS Webinterface builds env correctly
